// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace ControleEmprestimosLivros.AspNet.Core.MVC.DATA.Models
{
    [Table("CLIENTES")]
    public partial class Clientes
    {
        public Clientes()
        {
            Livrosclientes = new HashSet<Livrosclientes>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [Column("CPF")]
        [StringLength(14)]
        [Display(Name = "CPF")]
        public string Cpf { get; set; }
        [Required]
        [Column("NOME")]
        [StringLength(100)]
        public string Nome { get; set; }
        [Required]
        [Column("ENDERECO")]
        [StringLength(50)]
        [Display(Name = "Endereço")]

        public string Endereco { get; set; }
        [Required]
        [Column("CIDADE")]
        [StringLength(50)]
        public string Cidade { get; set; }
        [Required]
        [Column("BAIRRO")]
        [StringLength(50)]
        public string Bairro { get; set; }
        [Column("NUMERO")]
        [StringLength(50)]
        [Display(Name = "Número")]
        public string Numero { get; set; }
        [Column("TELCELULAR")]
        [StringLength(14)]
        [Display(Name = "Celular")]
        public string Telcelular { get; set; }
        [Column("TELFIXO")]
        [StringLength(13)]
        [Display(Name = "Telefone")]
        public string Telfixo { get; set; }

        [InverseProperty("Cliente")]
        public virtual ICollection<Livrosclientes> Livrosclientes { get; set; }
    }
}