// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ControleEmprestimosLivros.AspNet.Core.MVC.DATA.Models
{
    [Table("LIVROSCLIENTES")]
    public partial class Livrosclientes
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("LIVROID")]
        public int Livroid { get; set; }
        [Column("CLIENTEID")]
        public int Clienteid { get; set; }
        [Column("DATAEMPRESTIMO", TypeName = "datetime")]
        public DateTime Dataemprestimo { get; set; }
        [Column("DATADEVOLUCAO", TypeName = "datetime")]
        public DateTime Datadevolucao { get; set; }
        [Column("ENTREGUE")]
        public bool Entregue { get; set; }

        [ForeignKey(nameof(Clienteid))]
        [InverseProperty(nameof(Clientes.Livrosclientes))]
        public virtual Clientes Cliente { get; set; }
        [ForeignKey(nameof(Livroid))]
        [InverseProperty(nameof(Livros.Livrosclientes))]
        public virtual Livros Livro { get; set; }
    }
}